//! Shared test-harness utilities for tool integration tests.
//!
//! Each per-tool test file invokes the dispatcher exactly the way the
//! orchestrator does at runtime — JSON in, JSON out.  Tests use [`invoke`] for
//! stateless calls (a fresh `ToolContext` is created per call) or
//! [`invoke_with_ctx`] for lifecycle tests that need state to persist across
//! multiple tool calls (open → use → close patterns).
//!
//! [`expect_success`] asserts the response has no `"error"` field.
//! [`expect_error`] asserts the response has `"error": "<code>"`.
//! [`assert_schema_matches_spec`] compares the schemars-generated JSON Schema
//! against a hand-written spec, stripping schemars-only annotations first.

#![allow(dead_code)] // Helpers are pulled into per-tool test binaries selectively.

use serde_json::{json, Value};
use zend_tools::ToolContext;

/// Invoke a tool by name with default `ToolContext`.
pub fn invoke(tool: &str, args: Value) -> Value {
    let ctx = ToolContext::new();
    invoke_with_ctx(tool, args, &ctx)
}

/// Invoke a tool by name, threading a caller-supplied context.
/// Use this when a test needs to pre-seed VFS, credentials, sessions, etc.
pub fn invoke_with_ctx(tool: &str, args: Value, ctx: &ToolContext) -> Value {
    zend_tools::run(tool, "test_call_id", &args, ctx)
}

/// Fetch the JSON schema produced by schemars for a registered tool.
pub fn schema(tool: &str) -> Value {
    let registered =
        zend_tools::registry::find(tool).unwrap_or_else(|| panic!("tool {tool:?} not registered"));
    (registered.schema)()
}

/// Confirmation details (if any) for a tool call. Mirrors the runtime call.
pub fn confirmation(tool: &str, args: Value) -> Option<zend_tools::ConfirmationDetails> {
    zend_tools::confirmation(tool, &args)
}

// ── Assertions ────────────────────────────────────────────────────────────────

/// Assert that the response is an error envelope with the given code.
/// Returns the `detail` string for further assertions.
#[track_caller]
pub fn expect_error(response: &Value, expected_code: &str) -> String {
    let code = response
        .get("error")
        .and_then(Value::as_str)
        .unwrap_or_else(|| {
            panic!("expected error response with code {expected_code:?}, got: {response}",)
        });
    assert_eq!(
        code, expected_code,
        "expected error code {expected_code:?}, got {code:?}: {response}",
    );
    response
        .get("detail")
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string()
}

/// Assert that the response is *not* an error envelope. Returns it.
#[track_caller]
pub fn expect_success(response: Value) -> Value {
    if response.get("error").is_some() {
        panic!("expected success, got error: {response}");
    }
    response
}

// ── Schema assertions ─────────────────────────────────────────────────────────

/// Assert that the schema generated by schemars for `tool` matches the
/// hand-written specification, modulo schemars-only metadata.
///
/// The match is structural: keys are sorted, schemars-only annotations
/// (`title`, `$schema`, `definitions`/`$defs` for inlined types) are stripped
/// before comparison.
#[track_caller]
pub fn assert_schema_matches_spec(tool: &str, expected_json: &str) {
    let actual = schema(tool);
    let expected: Value = serde_json::from_str(expected_json)
        .unwrap_or_else(|e| panic!("invalid expected schema JSON: {e}"));
    let actual_norm = normalize_schema(&actual);
    let expected_norm = normalize_schema(&expected);
    if actual_norm != expected_norm {
        panic!(
            "schema mismatch for tool {tool:?}\n\nactual (normalized):\n{}\n\nexpected (normalized):\n{}",
            serde_json::to_string_pretty(&actual_norm).unwrap(),
            serde_json::to_string_pretty(&expected_norm).unwrap(),
        );
    }
}

/// Strip schemars-only metadata so generated schemas compare cleanly to the
/// hand-written specs in `docs/tool-system.md`.
fn normalize_schema(v: &Value) -> Value {
    match v {
        Value::Object(map) => {
            let mut out = serde_json::Map::new();
            for (k, vv) in map {
                if matches!(k.as_str(), "title" | "$schema" | "definitions" | "$defs") {
                    continue;
                }
                out.insert(k.clone(), normalize_schema(vv));
            }
            Value::Object(out)
        }
        Value::Array(items) => Value::Array(items.iter().map(normalize_schema).collect()),
        _ => v.clone(),
    }
}

// ── Smoke test for the harness itself ─────────────────────────────────────────

/// A canonical "unknown tool" response, useful as a sanity check.
pub fn unknown_tool_response(name: &str) -> Value {
    json!({
        "error": "unknown_tool",
        "detail": format!("no tool registered with name {name:?}"),
    })
}
