//! Tool-catalog summary: the `tools` collection's grouped catalog listing.
//!
//! The summary text is a **pure, deterministic function of the catalog** — each
//! tool is grouped under its [`zend_tools::registry::category_for`] category and
//! listed by name — so it is assembled directly and prefilled on every startup,
//! never generated by a model and never cached. [`build_tool_summary`] does the
//! assembly.

use std::collections::HashMap;

use candle_conversation::projection::SectionId;
use zend_tools::registry::category_for;

/// One installed tool: `(name, section_id, json_line)` — the triple
/// [`crate::tools::install_tool_catalog`] returns, in registry order.
pub type InstalledTool = (String, SectionId, String);

/// Assemble the tool-catalog summary deterministically: group the tools by
/// [`category_for`] and render one `## <category>` block per group, each listing
/// its tools by name in catalog order. Categories appear in first-appearance
/// (registry) order, so the layout mirrors `register_all`. No model call — the
/// text depends only on the catalog.
pub fn build_tool_summary(tools: &[InstalledTool]) -> String {
    // Group by category, preserving first-appearance order (== registry order,
    // since each category's tools are contiguous in the catalog).
    let mut order: Vec<&str> = Vec::new();
    let mut groups: HashMap<&str, Vec<&str>> = HashMap::new();
    for (name, _, _) in tools {
        let cat = category_for(name);
        if !groups.contains_key(cat) {
            order.push(cat);
            groups.insert(cat, Vec::new());
        }
        groups.get_mut(cat).unwrap().push(name.as_str());
    }

    let mut out = String::new();
    for cat in order {
        if let Some(names) = groups.get(cat) {
            out.push_str(&format!("## {cat}\n  {}\n", names.join(", ")));
        }
    }
    out.trim_end().to_string()
}

/// Rebuild the mode-appropriate tool-catalog summary straight from the registry —
/// the same text the startup seals, without needing the installed-section
/// handles. `restricted` selects the safe (non-high-risk) subset. Used by the
/// projection panel to display the injected summary on demand.
pub fn tool_summary_for_mode(restricted: bool) -> String {
    let safe = crate::tools::safe_tool_names();
    // `build_tool_summary` reads only the name — the section id / json are unused
    // here, so a placeholder id is fine (it must be non-zero: `SectionId::new`
    // rejects 0).
    let tools: Vec<InstalledTool> = zend_tools::registry::all_tools()
        .iter()
        .map(|t| t.name)
        .filter(|name| !restricted || safe.contains(*name))
        .map(|name| (name.to_string(), SectionId::new(1), String::new()))
        .collect();
    build_tool_summary(&tools)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tool(name: &str) -> InstalledTool {
        (
            name.to_string(),
            SectionId::new(1),
            format!("{{\"name\":\"{name}\",\"parameters\":{{}}}}"),
        )
    }

    #[test]
    fn build_groups_by_category_in_registry_order() {
        // Two categories, interleaved input order within each preserved; category
        // order is first-appearance.
        let tools = vec![
            tool("datetime"),   // Utilities & web
            tool("file_read"),  // Files
            tool("calculator"), // Utilities & web
            tool("bytes_xor"),  // Byte encoding
        ];
        let out = build_tool_summary(&tools);
        assert_eq!(
            out,
            "## Utilities & web\n  datetime, calculator\n\
             ## Files\n  file_read\n\
             ## Byte encoding\n  bytes_xor"
        );
    }

    #[test]
    fn build_empty_is_empty() {
        assert_eq!(build_tool_summary(&[]), "");
    }
}
