//! Compile-time-embedded calibration trajectories — the `examples/*.md` files
//! produced by the `export_calibration` tool, keyed by `(tool, example_index)`.
//!
//! The prefill-based calibration path loads a tool example's decoded trajectory
//! here instead of re-decoding it: strip the [`PROJECTION_MARKER`]s, split off
//! the assistant body, and prefill it verbatim (see
//! `Sequence::submit_prefilled_turn`). The `TRAJECTORIES` table is generated by
//! `build.rs`.

// `pub static TRAJECTORIES: &[(&str, usize, &str)]` — (tool, 1-based index, text).
include!(concat!(env!("OUT_DIR"), "/calibration_trajectories.rs"));

/// The marker `export_calibration` inserts at each projection point. It is NOT a
/// real token — strip it before prefill; its positions define the reconstructed
/// projection-event spans.
pub const PROJECTION_MARKER: &str = "<|projection|>";

/// The verbatim exported trajectory for `(tool, index)` (1-based), or `None` if
/// that example was never exported.
pub fn trajectory_for(tool: &str, index: usize) -> Option<&'static str> {
    TRAJECTORIES
        .iter()
        .find(|(t, i, _)| *t == tool && *i == index)
        .map(|(_, _, s)| *s)
}

/// Total number of embedded trajectories.
pub fn count() -> usize {
    TRAJECTORIES.len()
}
