//! Projection harness: validates the BDP scanner + projection pipeline
//! using real Qwen3-30B-A3B Q-vector provenance data.
//!
//! # Module layout
//!
//!   corpus              — test data types, fixture loader, YAML helper, tool stubs
//!   resolver            — HarnessResolver: minimal ContentResolver backed by BDP scores
//!   harness             — Harness: builder setup, scan, scoring, projection helpers
//!
//!   cases/tools_layer         — 8-tool discrimination and projection top-3 selection
//!   cases/file_layer          — file_read vs file_write fine-discrimination tests
//!   cases/conversation_layer  — positive > boundary > negative probe quality ordering
//!   cases/report              — 8×8 score matrix + ratio report (non-assertion, --nocapture)
//!
//! # Data
//!
//! Reads `tests/tool_provenance_real_data/` — real Q-vector sign-bit
//! signatures from Qwen3-30B-A3B-Q4_K_M generated by `gen_real_provenance_data`.
//!
//! Run:
//!   cargo test -p candle-conversation --test projection_harness -- --nocapture

mod corpus;
mod harness;
mod resolver;

mod cases {
    mod conversation_layer;
    mod file_layer;
    mod formula_comparison;
    mod formula_experiments;
    mod prefill_formula_comparison;
    mod production_query_diagnostic;
    mod raw_strategy_comparison;
    mod report;
    mod tools_layer;
}

use corpus::TOOLS;
use harness::Harness;

// ── Sanity ─────────────────────────────────────────────────────────────────────

#[test]
fn harness_builds_with_all_tool_sections() {
    let h = Harness::build();
    assert_eq!(h.tool_section_ids.len(), TOOLS.len());
    for &tool in TOOLS {
        assert!(h.tool_section_ids.contains_key(tool), "missing section for {tool}");
    }
}
